// HR/EN prevodi za GSE Control
export type Language = 'hr' | 'en'

export const translations = {
  hr: {
    'app.name': 'GSE Control', 'app.tagline': 'Skeniraj QR kod na opremi', 'app.loading': 'Učitavanje...',
    'nav.radnik': 'Radnik', 'nav.dashboard': 'Dashboard', 'nav.fids': 'FIDS', 'nav.about': 'O nama', 'nav.features': 'Funkcije', 'nav.odjava': 'Odjava', 'nav.radnikView': 'Radnik view', 'nav.home': 'Početna',
    'landing.badge': 'IATA AHM 340 + EASA Part-145 Compliant', 'landing.featuresTitle': 'GSE Control — Ground Support Equipment Management', 'landing.featuresSubtitle': 'Kompletan sistem za upravljanje GSE opremom na aerodromu — od QR skeniranja do EASA compliance izvještaja', 'landing.rolesTitle': '3 nivoa pristupa', 'landing.workerTitle': 'Radnik', 'landing.workerDesc': 'Radnici skeniraju QR kod i unose PIN — bez login-a, brzo i jednostavno', 'landing.dashboardTitle': 'Dashboard', 'landing.dashboardDesc': 'Dashboard sa 10 tabova: oprema, oštećenja, statistika, izvještaji, EASA compliance', 'landing.damagesTitle': 'Oštećenja', 'landing.damagesDesc': 'Automatsko blokiranje neispravne opreme sa foto dokazima i root cause analysis', 'landing.reportsTitle': 'Izvještaji', 'landing.reportsDesc': 'PDF izvještaji (dnevni, mjesečni, godišnji) — spremni za audit', 'landing.operatorTitle': 'Operator', 'landing.engineerTitle': 'Inženjer', 'landing.adminTitle': 'Administrator', 'landing.demoMode': 'Demo Mode — Mock podaci', 'landing.footer': 'GSE Control · IATA AHM 340 + EASA Part-145 compliant', 'landing.getStarted': 'Započni skeniranje', 'landing.learnMore': 'Saznaj više',
    'about.title': 'O aplikaciji', 'about.subtitle': 'Razvijeno za aerodrome, od strane avijatičara', 'about.developerTitle': 'O programeru', 'about.developerName': 'Programer za Aerodrom Tivat', 'about.experience': '25 godina iskustva u avijaciji', 'about.developerBio': 'Sa 25 godina iskustva u avijaciji i radom na Aerodromu Tivat, razvio sam GSE Control kao odgovor na stvarne potrebe aerodromske platforme. Sistem je dizajniran na osnovu praktičnog znanja o GSE operacijama, IATA standardima i EASA regulativi, sa ciljem da pojednostavi svakodnevni rad osoblja na platformi.', 'about.techTitle': 'Tehnologija', 'about.techSubtitle': 'Moderni tech stack za pouzdanost i skalabilnost', 'about.missionTitle': 'Misija', 'about.missionText': 'Pojednostaviti upravljanje GSE opremom na aerodromima kroz digitalizaciju, automatizaciju i compliance sa međunarodnim standardima.',
    'features.title': 'Funkcije sistema', 'features.subtitle': 'Kompletan GSE management sistem u skladu sa IATA i EASA regulativom', 'features.complianceTitle': 'Regulativa i compliance', 'features.coreTitle': 'Osnovne funkcije', 'features.advancedTitle': 'Napredne funkcije', 'features.techTitle': 'Tehničke karakteristike',
    'worker.title': 'Zaduži / Razduži sredstvo', 'worker.subtitle': 'Skenirajte QR kod sa vozila ili opreme', 'worker.howItWorks': 'Kako radi?', 'worker.step1': 'Skeniraj QR kod na vozilu/opremi', 'worker.step2': 'Unesi PIN ili broj ID kartice', 'worker.step3': 'Pregledaj i potvrdi checklistu', 'worker.step4': 'Prijava završena — sredstvo je zaduženo', 'worker.scanCode': 'Skeniranje QR koda', 'worker.scanning': 'Skeniram...', 'worker.startCamera': 'Pokreni kameru', 'worker.stopCamera': 'Zaustavi', 'worker.manual': 'Ručno', 'worker.manualInput': 'Ručni unos koda', 'worker.confirm': 'Potvrdi', 'worker.camera': 'Kamera', 'worker.noCamera': 'Kamera nije dostupna. Koristite ručni unos.', 'worker.cameraError': 'Ne mogu pristupiti kameri', 'worker.cameraStartError': 'Greška pri pokretanju kamere',
    'worker.identification': 'Identifikacija radnika', 'worker.pin': 'PIN (najbrže — unesite svoj 4-cifreni PIN)', 'worker.pinPlaceholder': 'npr. 1001', 'worker.identify': 'Identifikuj', 'worker.identified': 'Identifikovani', 'worker.welcome': 'Dobrodošli', 'worker.orManual': 'ILI ručno unesite', 'worker.cardId': 'Broj ID kartice *', 'worker.cardIdPlaceholder': 'npr. EMP-1001', 'worker.empName': 'Ime i prezime *', 'worker.empNamePlaceholder': 'npr. Vukan Vojvodić', 'worker.continueToInspection': 'Nastavi na pregled', 'worker.continueToCheckin': 'Nastavi na razduživanje', 'worker.back': 'Nazad', 'worker.step': 'Korak',
    'worker.equipment': 'Oprema', 'worker.location': 'Lokacija', 'worker.status': 'Status', 'worker.checklist': 'Pre-use inspection checklista', 'worker.checklistHint': 'Označite svaku stavku kao ispravnu ili neispravnu', 'worker.ok': 'Ispravno', 'worker.notOk': 'Neispravno', 'worker.inspectionResult': 'Rezultat pregleda', 'worker.resultOk': 'Ispravno', 'worker.resultMinor': 'Manje oštećenje', 'worker.resultMajor': 'Veće oštećenje', 'worker.resultOos': 'Neispravno', 'worker.damageDescription': 'Opis oštećenja *', 'worker.damagePlaceholder': 'Detaljno opišite šta je neispravno ili oštećeno...', 'worker.severity': 'Težina oštećenja', 'worker.severityMinor': 'Manje', 'worker.severityMajor': 'Veće', 'worker.severityCritical': 'Kritično', 'worker.photoEvidence': 'Fotografija oštećenja (preporučeno)', 'worker.takePhoto': 'Slikaj', 'worker.selectImage': 'Izaberi sliku', 'worker.notes': 'Dodatne napomene (opciono)', 'worker.notesPlaceholder': 'Opciono: bilješke o stanju...', 'worker.checkout': 'Zaduži sredstvo', 'worker.checkin': 'Razduži sredstvo', 'worker.checkoutAction': 'Zaduživanje', 'worker.checkinAction': 'Razduživanje',
    'worker.checkoutSuccess': 'Uspješno zaduženo!', 'worker.checkinSuccess': 'Uspješno razduženo!', 'worker.checkoutSuccessMsg': 'Preuzeli ste odgovornost za sredstvo tokom smjene.', 'worker.checkinSuccessMsg': 'Sredstvo je vraćeno u dostupne.', 'worker.scanNext': 'Skeniraj sljedeće', 'worker.blocked': 'Zaduživanje blokirano', 'worker.blockedMsg': 'Sredstvo je neispravno ili je već na održavanju.', 'worker.scanOther': 'Skeniraj drugo sredstvo', 'worker.reportedDamage': 'Prijavili ste oštećenje na sredstvu. Sredstvo je prebačeno u status "Neispravno" i ne može se zadužiti. Održavanje je automatski obaviješteno o vašoj prijavi.', 'worker.alreadyOos': 'Sredstvo je trenutno neispravno ili je na održavanju. Zaduživanje nije moguće. Kontaktirajte održavanje ako smatrate da je greška.', 'worker.currentStatus': 'Trenutni status', 'worker.reportedDamageLabel': 'Prijavljeno oštećenje', 'worker.severityLabel': 'Težina', 'worker.reasonLabel': 'Razlog',
    'worker.checkinTitle': 'Razduživanje', 'worker.checkinConfirm': 'Potvrđujete da razdužujete ovo sredstvo i da ste ga vratili u istom stanju (ili prijavljujete novo oštećenje).', 'worker.newDamage': 'Dali ste primijetili novo oštećenje?', 'worker.noAllOk': 'Ne, sve OK', 'worker.yesReport': 'Da, prijavljujem', 'worker.describeDamage': 'Opišite novo oštećenje...', 'worker.checkinNotes': 'Napomene (opciono)',
    'status.available': 'Dostupno', 'status.assigned': 'Zaduženo', 'status.out_of_service': 'Neispravno', 'status.maintenance': 'Na održavanju',
    'login.title': 'Prijava', 'login.email': 'Email', 'login.password': 'Lozinka', 'login.submit': 'Prijavi se', 'login.demoMode': 'Demo Mode — Supabase nije konfigurisan', 'login.demoUsers': 'Demo korisnici (jedan klik za prijavu)', 'login.demoPassword': 'Lozinka za sve demo korisnike',
    'dash.title': 'GSE Control — Dashboard', 'dash.overview': 'Pregled', 'dash.equipment': 'Oprema', 'dash.damages': 'Oštećenja', 'dash.statistics': 'Statistika', 'dash.maintenance': 'Održavanje', 'dash.compliance': 'EASA Compliance', 'dash.analytics': 'Analytics', 'dash.reports': 'Izvještaji', 'dash.activity': 'Aktivnost', 'dash.qr': 'QR kodovi', 'dash.refresh': 'Osvježi', 'dash.newEquipment': 'Novo sredstvo', 'dash.bulkImport': 'Bulk import CSV', 'dash.total': 'Ukupno', 'dash.available': 'Dostupno', 'dash.assigned': 'Zaduženo', 'dash.oos': 'Neispravno', 'dash.openDamages': 'Otvorena oštećenja', 'dash.activeAssignments': 'Trenutno zadužena sredstva', 'dash.noActiveAssignments': 'Trenutno nema zaduženih sredstava', 'dash.allDamages': 'Sva oštećenja', 'dash.noDamages': 'Nema prijavljenih oštećenja', 'dash.recentActivity': 'Zadnje aktivnosti', 'dash.noActivity': 'Nema zabilježenih aktivnosti', 'dash.qrPrint': 'QR kodovi za štampu',
    'fids.title': 'AERODROMSKI GSE FIDS', 'fids.subtitle': 'Ground Support Equipment — Real-time Status Display', 'fids.localTime': 'Lokalno vrijeme', 'fids.total': 'UKUPNO', 'fids.inUse': 'U UPOTREBI', 'fids.available': 'DOSTUPNO', 'fids.outOfService': 'NEISPRAVNO', 'fids.maintenance': 'ODRŽAVANJE', 'fids.statusBoard': 'Status Board', 'fids.byType': 'Pregled po tipu opreme', 'fids.code': 'Kod', 'fids.name': 'Naziv', 'fids.type': 'Tip', 'fids.location': 'Lokacija', 'fids.status': 'Status', 'fids.loading': 'Učitavanje...', 'fids.noData': 'Nema dostupnih podataka', 'fids.lastUpdate': 'Zadnje ažuriranje', 'fids.autoRefresh': 'Auto-refresh: 30s', 'fids.use': 'Upotreba', 'fids.free': 'Slobodno', 'fids.broken': 'Neispravno', 'fids.maint': 'Održav.', 'fids.more': 'više', 'fids.inUseStatus': '● U UPOTREBI', 'fids.availableStatus': '✓ DOSTUPNO', 'fids.oosStatus': '✗ NEISPRAVNO', 'fids.maintStatus': '⚙ ODRŽAVANJE', 'fids.refresh': 'Osvježi',
  },
  en: {
    'app.name': 'GSE Control', 'app.tagline': 'Scan QR code on equipment', 'app.loading': 'Loading...',
    'nav.radnik': 'Worker', 'nav.dashboard': 'Dashboard', 'nav.fids': 'FIDS', 'nav.about': 'About', 'nav.features': 'Features', 'nav.odjava': 'Logout', 'nav.radnikView': 'Worker view', 'nav.home': 'Home',
    'landing.badge': 'IATA AHM 340 + EASA Part-145 Compliant', 'landing.featuresTitle': 'GSE Control — Ground Support Equipment Management', 'landing.featuresSubtitle': 'Complete GSE management system for airports — from QR scanning to EASA compliance reports', 'landing.rolesTitle': '3 access levels', 'landing.workerTitle': 'Worker', 'landing.workerDesc': 'Workers scan QR code and enter PIN — no login required, fast and simple', 'landing.dashboardTitle': 'Dashboard', 'landing.dashboardDesc': 'Dashboard with 10 tabs: equipment, damages, statistics, reports, EASA compliance', 'landing.damagesTitle': 'Damages', 'landing.damagesDesc': 'Automatic blocking of faulty equipment with photo evidence and root cause analysis', 'landing.reportsTitle': 'Reports', 'landing.reportsDesc': 'PDF reports (daily, monthly, yearly) — audit ready', 'landing.operatorTitle': 'Operator', 'landing.engineerTitle': 'Engineer', 'landing.adminTitle': 'Administrator', 'landing.demoMode': 'Demo Mode — Mock data', 'landing.footer': 'GSE Control · IATA AHM 340 + EASA Part-145 compliant', 'landing.getStarted': 'Start scanning', 'landing.learnMore': 'Learn more',
    'about.title': 'About', 'about.subtitle': 'Built for airports, by an aviation professional', 'about.developerTitle': 'About the developer', 'about.developerName': 'Developer at Tivat Airport', 'about.experience': '25 years of aviation experience', 'about.developerBio': 'With 25 years of experience in aviation and working at Tivat Airport, I developed GSE Control as a response to real airport ramp needs. The system is designed based on practical knowledge of GSE operations, IATA standards and EASA regulations, with the goal of simplifying the daily work of ramp personnel.', 'about.techTitle': 'Technology', 'about.techSubtitle': 'Modern tech stack for reliability and scalability', 'about.missionTitle': 'Mission', 'about.missionText': 'Simplify GSE equipment management at airports through digitalization, automation and compliance with international standards.',
    'features.title': 'System Features', 'features.subtitle': 'Complete GSE management system compliant with IATA and EASA regulations', 'features.complianceTitle': 'Regulations & Compliance', 'features.coreTitle': 'Core Features', 'features.advancedTitle': 'Advanced Features', 'features.techTitle': 'Technical Features',
    'worker.title': 'Check out / Check in equipment', 'worker.subtitle': 'Scan QR code from vehicle or equipment', 'worker.howItWorks': 'How it works?', 'worker.step1': 'Scan QR code on vehicle/equipment', 'worker.step2': 'Enter PIN or ID card number', 'worker.step3': 'Review and confirm checklist', 'worker.step4': 'Done — equipment is checked out', 'worker.scanCode': 'QR Code Scanning', 'worker.scanning': 'Scanning...', 'worker.startCamera': 'Start camera', 'worker.stopCamera': 'Stop', 'worker.manual': 'Manual', 'worker.manualInput': 'Manual code entry', 'worker.confirm': 'Confirm', 'worker.camera': 'Camera', 'worker.noCamera': 'Camera not available. Use manual entry.', 'worker.cameraError': 'Cannot access camera', 'worker.cameraStartError': 'Error starting camera',
    'worker.identification': 'Worker identification', 'worker.pin': 'PIN (fastest — enter your 4-digit PIN)', 'worker.pinPlaceholder': 'e.g. 1001', 'worker.identify': 'Identify', 'worker.identified': 'Identified', 'worker.welcome': 'Welcome', 'worker.orManual': 'OR enter manually', 'worker.cardId': 'ID card number *', 'worker.cardIdPlaceholder': 'e.g. EMP-1001', 'worker.empName': 'Full name *', 'worker.empNamePlaceholder': 'e.g. John Smith', 'worker.continueToInspection': 'Continue to inspection', 'worker.continueToCheckin': 'Continue to check-in', 'worker.back': 'Back', 'worker.step': 'Step',
    'worker.equipment': 'Equipment', 'worker.location': 'Location', 'worker.status': 'Status', 'worker.checklist': 'Pre-use inspection checklist', 'worker.checklistHint': 'Mark each item as OK or Not OK', 'worker.ok': 'OK', 'worker.notOk': 'Not OK', 'worker.inspectionResult': 'Inspection result', 'worker.resultOk': 'OK', 'worker.resultMinor': 'Minor damage', 'worker.resultMajor': 'Major damage', 'worker.resultOos': 'Out of service', 'worker.damageDescription': 'Damage description *', 'worker.damagePlaceholder': 'Describe in detail what is damaged...', 'worker.severity': 'Damage severity', 'worker.severityMinor': 'Minor', 'worker.severityMajor': 'Major', 'worker.severityCritical': 'Critical', 'worker.photoEvidence': 'Damage photo (recommended)', 'worker.takePhoto': 'Take photo', 'worker.selectImage': 'Select image', 'worker.notes': 'Additional notes (optional)', 'worker.notesPlaceholder': 'Optional: condition notes...', 'worker.checkout': 'Check out equipment', 'worker.checkin': 'Check in equipment', 'worker.checkoutAction': 'Check-out', 'worker.checkinAction': 'Check-in',
    'worker.checkoutSuccess': 'Successfully checked out!', 'worker.checkinSuccess': 'Successfully checked in!', 'worker.checkoutSuccessMsg': 'You have taken responsibility for this equipment during your shift.', 'worker.checkinSuccessMsg': 'Equipment returned to available.', 'worker.scanNext': 'Scan next', 'worker.blocked': 'Check-out blocked', 'worker.blockedMsg': 'Equipment is out of service or under maintenance.', 'worker.scanOther': 'Scan other equipment', 'worker.reportedDamage': 'You reported damage on this equipment. It has been moved to "Out of service" status and cannot be checked out. Maintenance has been automatically notified.', 'worker.alreadyOos': 'Equipment is currently out of service or under maintenance. Check-out is not possible. Contact maintenance if you believe this is an error.', 'worker.currentStatus': 'Current status', 'worker.reportedDamageLabel': 'Reported damage', 'worker.severityLabel': 'Severity', 'worker.reasonLabel': 'Reason',
    'worker.checkinTitle': 'Check-in', 'worker.checkinConfirm': 'You confirm you are checking in this equipment in the same condition (or reporting new damage).', 'worker.newDamage': 'Did you notice new damage?', 'worker.noAllOk': 'No, all OK', 'worker.yesReport': 'Yes, reporting', 'worker.describeDamage': 'Describe new damage...', 'worker.checkinNotes': 'Notes (optional)',
    'status.available': 'Available', 'status.assigned': 'Assigned', 'status.out_of_service': 'Out of service', 'status.maintenance': 'Maintenance',
    'login.title': 'Login', 'login.email': 'Email', 'login.password': 'Password', 'login.submit': 'Sign in', 'login.demoMode': 'Demo Mode — Supabase not configured', 'login.demoUsers': 'Demo users (one click login)', 'login.demoPassword': 'Password for all demo users',
    'dash.title': 'GSE Control — Dashboard', 'dash.overview': 'Overview', 'dash.equipment': 'Equipment', 'dash.damages': 'Damages', 'dash.statistics': 'Statistics', 'dash.maintenance': 'Maintenance', 'dash.compliance': 'EASA Compliance', 'dash.analytics': 'Analytics', 'dash.reports': 'Reports', 'dash.activity': 'Activity', 'dash.qr': 'QR Codes', 'dash.refresh': 'Refresh', 'dash.newEquipment': 'New equipment', 'dash.bulkImport': 'Bulk import CSV',
    'dash.total': 'Total', 'dash.available': 'Available', 'dash.assigned': 'Assigned', 'dash.oos': 'Out of service', 'dash.openDamages': 'Open damages', 'dash.activeAssignments': 'Currently assigned equipment', 'dash.noActiveAssignments': 'No equipment currently assigned', 'dash.allDamages': 'All damages', 'dash.noDamages': 'No damages reported', 'dash.recentActivity': 'Recent activity', 'dash.noActivity': 'No activity recorded', 'dash.qrPrint': 'QR codes for printing',
    'fids.title': 'AIRPORT GSE FIDS', 'fids.subtitle': 'Ground Support Equipment — Real-time Status Display', 'fids.localTime': 'Local time', 'fids.total': 'TOTAL', 'fids.inUse': 'IN USE', 'fids.available': 'AVAILABLE', 'fids.outOfService': 'OUT OF SERVICE', 'fids.maintenance': 'MAINTENANCE', 'fids.statusBoard': 'Status Board', 'fids.byType': 'Overview by equipment type', 'fids.code': 'Code', 'fids.name': 'Name', 'fids.type': 'Type', 'fids.location': 'Location', 'fids.status': 'Status', 'fids.loading': 'Loading...', 'fids.noData': 'No data available', 'fids.lastUpdate': 'Last updated', 'fids.autoRefresh': 'Auto-refresh: 30s', 'fids.use': 'In use', 'fids.free': 'Free', 'fids.broken': 'Broken', 'fids.maint': 'Maint.', 'fids.more': 'more', 'fids.inUseStatus': '● IN USE', 'fids.availableStatus': '✓ AVAILABLE', 'fids.oosStatus': '✗ OUT OF SERVICE', 'fids.maintStatus': '⚙ MAINTENANCE', 'fids.refresh': 'Refresh',
  },
} as const

export type TranslationKey = keyof typeof translations['hr']
